export const LOAD_PRODUCTS = 'LOAD_PRODUCTS' 
export const SET_OPEN_DETAIL = 'SET_OPEN_DETAIL' 
export const SET_PRODUCT_EDIT = 'SET_PRODUCT_EDIT' 
export const SET_NAME_PRODUCT_EDIT = 'SET_NAME_PRODUCT_EDIT' 
export const SET_DESCRIPTION_PRODUCT_EDIT = 'SET_DESCRIPTION_PRODUCT_EDIT' 
export const SET_CATEGORY_PRODUCT_EDIT = 'SET_CATEGORY_PRODUCT_EDIT' 

